version: '3.8'

services:
  auth-service-api:
    container_name: auth-service-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5041:5041"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure