name: CI pipeline

on:      
  pull_request:
    branches:
      [main]
    types:
      [opened, synchronize, reopened]

env:
  CONFIGURATION: Release
  SOLUTION_FILE_PATH: ./Meetme.AuthService/Meetme.AuthService.sln
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.organization=ArtMironowProjects
            -Dsonar.projectKey=ArtMironow_Meetme.AuthService
